@startuml
'https://plantuml.com/use-case-diagram
left to right direction
skinparam linetype ortho

rectangle "Вход в систему" {
usecase "Регистрация" as registration
usecase "Авторизация" as authorization
}

rectangle "Чат" {
usecase "Войти в чат" as start_chat
usecase "Получить информацию о чате" as get_chat_info
usecase "Покинуть чат" as leave_chat
usecase "Вернуться в чат" as back_chat
usecase "Получить всех пользователей чата" as get_chat_members
usecase "Отправить сообщение" as send_message
usecase "Получить сообщение чата" as get_chat_message
}

rectangle "Администрирование чата" {
usecase "Созадть чат" as create_chat
usecase "Удалить чат" as delete_chat
usecase "Пригласить пользователя" as invite_user
usecase "Выгнать пользоавтеля" as kick_user
usecase "Изменить чат" as change_chat
}


:Гость: as Guest

 Guest -- registration

:Пользователь: as User

User -- start_chat
User ----- authorization

:Участник чата: as Chat_member


Chat_member -- get_chat_info
Chat_member -- leave_chat
Chat_member -- back_chat
Chat_member -- get_chat_members
Chat_member -- send_message
Chat_member -- get_chat_message

:Создатель чата: as Super_User

Super_User -- create_chat
Super_User -- delete_chat
Super_User -- invite_user
Super_User -- kick_user
Super_User -- change_chat


Chat_member ----|> Super_User
User --|> Chat_member
@enduml